name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      couchbase:
        image: couchbase
        ports:
          - 8091-8095:8091-8095
          - 11210:11210

    steps:
      - name: Configure core dump capturing
        run: |
          echo '/tmp/core.%h.%e.%t' | sudo tee /proc/sys/kernel/core_pattern

      - name: Install build environment
        run: sudo apt-get install -y gdb

      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install dependencies
        run: bundle install

      - name: Initialize couchbase
        run: ./bin/init-cluster

      - name: Check couchbase
        run: SLEEP=15 ./bin/check-cluster

      - name: Display library version
        run: bundle exec ruby -I lib -r 'couchbase/model' -e 'pp Couchbase::VERSION'

      - name: Run tests
        timeout-minutes: 15
        run: |
          ulimit -c unlimited
          bundle exec rake test

      - name: Display core dumps
        if: ${{ failure() }}
        run: |
          for i in /tmp/core*
          do
             if [ -f $i ]
             then
               echo $i
               file $i
               gdb $(bundle exec which ruby) $i --batch -ex "thread apply all bt"
             fi
          done
